nome: Pipeline de Teste dos Arquivos Terraform

on:
  workflow_dispatch:

jobs:
  testa-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Modifica o bin√°rio
        run: chmod +x ./scripts/valida-tf.sh

      - name: Chama o script
        run: ./scripts/valida-tf.sh